### ISSUE TITLE
Is `can_out_strm_list_by_id` `can` or not?

### ISSUE THREAD

**Issue by epage** [ni/nixnet-python#114]
The C header file defines `nxPropSession_IntfCANOutStrmListById` but the online help defines [`nxPropSession_IntfOutStrmListById`](http://zone.ni.com/reference/en-XX/help/372841L-01/nixnet/nxpropsession_intfoutstrmlistbyid/).

Which should it be?

**Comment by lilesj** [comment]
For now it should be nxPropSession_IntfCANOutStrmListById to be compatible with the existing headers. I will file a CAR to have an additional include added to the header file to match the documentation.

**Comment by epage** [comment]
>  will file a CAR to have an additional include added to the header file to match the documentation.

So `nxPropSession_IntfOutStrmListById` (no `Can`) is the more correct name?

Huh, didn't think to check LV.  It aligns with the documentation.

> For now it should be nxPropSession_IntfCANOutStrmListById to be compatible with the existing headers.

I'm not aware of any problem with us deviating from C especially since it'd be us aligning with docs/LV.  You have concerns with just changing it now?

**Comment by lilesj** [comment]
Both the documentation and LV match with the "no CAN" property name in addition to this property working for both CAN and LIN so it is more correct.

For the upper layer of the Python API we can and should deviate from the header and use the nxPropSession_IntfOutStrmListById  (no CAN) version. The lower level layers that interface with the driver should obviously continue to use the nxPropSession_IntfCANOutStrmListById  version since it is defined in the header file.
