### ISSUE TITLE
Should `can_out_strm_list_by_id` be raw data or parsed data?

### ISSUE THREAD

**Issue by epage** [ni/nixnet-python#115]
`can_out_strm_list_by_id` (might be renamed, see #114) deals with frame identifiers which are a bitmask. 

with frames, we give the user a choice of whether to use the raw id (`RawFrame`)( or the parsed id ([`CanFrame`](https://github.com/ni/nixnet-python/blob/master/nixnet/types.py#L139)).  Should we do the same here?

See http://zone.ni.com/reference/en-XX/help/372841L-01/nixnet/nxpropsession_intfoutstrmlistbyid/

**Comment by lilesj** [comment]
The replay frames are used to transmit a sequence of frames that were previously logged by a read operation. Since we provide the user with a choice of using the raw ID or a parsed ID when recording the frames it would probably be easier to use if we gave the user a similar choice for replay so their code can be reused in either case.
